CREATE TABLE person
(
    user_id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
    first_name VARCHAR(255)                                        NOT NULL,
    last_name  VARCHAR(255)                                        NOT NULL,
    birthday   DATE                                                NOT NULL,
    user_email VARCHAR(255)                                        NOT NULL,
    password   VARCHAR(255)                                        NOT NULL,
    roles      VARCHAR(255)                                        NOT NULL
);